ktor:
    application:
        modules:
            - jp.ikanoshiokara.ApplicationKt.module
    deployment:
        port: 8080
db:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/vooooote"
    user: "user"
    password: "password"
